# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        description: "Markdown linter"
        entry: markdownlint-cli2
        language: node
        files: \.md$
        require_serial: true
        args: ["--config", ".markdownlint-cli2.jsonc", "--fix"]
  - repo: local
    hooks:
      - id: check-markdown-links
        name: check-markdown-links
        description: "Check for broken file links in markdown files"
        entry: python3 scripts/check-markdown-links.py
        language: system
        files: \.md$
        pass_filenames: false
