code_review:
  comment_severity_threshold: MEDIUM
  pull_request_opened:
    summary: true
    code_review: true

ignore_patterns:
  - "node_modules/**"
  - ".git/**"
  - "*.log"
  - ".tmp/**"
  - "**/.terraform/**"
  - "**/venv/**"
  - "**/__pycache__/**"
