name: YAML Lint

on: [push, pull_request]

jobs:
  yaml-lint:
    name: "Lint YAML Files"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.0

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@ae1abb2821b567e96742aa776f7b62c9b6a26bc8  # v3.1.1
        with:
          file_or_dir: '.'
          config_file: .yamllint.yml
